apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-lb
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
