apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-mysql-instance-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: yc-network-hdd
  volumeName: backup-mysql-instance-pv
  resources:
    requests:
      storage: 2Gi
