---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-iscsi
  selector:
    matchExpressions:
      - key: name
        operator: In
        values: ["data-iscsi"]
