---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
  labels:
    name: data-iscsi
spec:
  storageClassName: csi-iscsi
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: iscsi.csi.k8s.io
    volumeHandle: iscsi-data-id
    volumeAttributes:
      targetPortal: "172.16.0.35:3260"
      portals: "[]"
      iqn: "iqn.2003-01.org.linux-iscsi.iscsi-12.x8664:sn.08ed7ab3e592"
      lun: "0"
      iscsiInterface: "default"
      discoveryCHAPAuth: "true"
      sessionCHAPAuth: "false"
