apiVersion: v1
kind: Service
metadata:
  name: nginx-with-exporter
  labels:
    app: nginx-with-exporter
spec:
  type: ClusterIP
  selector:
    app: nginx-with-exporter
  ports:
  - port: 80
    name: web
  - port: 9113
    name: metrics
