
stages:
- build_and_push

workflow:
  rules:
  - if: $CI_COMMIT_TAG
    when: always
  - when: never

.build_and_push:
  stage: build_and_push
  image: docker:24.0.7
  services:
  - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: ''
  script:
  - mkdir /root/.docker
  - |
    cat << JSON > /root/.docker/config.json
    { "auths": { "${REGISTRY_NAME}": { "auth": "${REGISTRY_AUTH}" } } }
    JSON
  - cd "${CI_PROJECT_DIR}/${DIR}"
  - IMAGE_TAG="${REGISTRY_NAME}/${REGISTRY_ID}/${SERVICE}:${CI_COMMIT_TAG}"
  - docker build --tag "${IMAGE_TAG}" .
  - docker push "${IMAGE_TAG}"

build_and_push_adservice:
  extends: .build_and_push
  variables:
    SERVICE: adservice
    DIR: src/${SERVICE}

build_and_push_cartservice:
  extends: .build_and_push
  variables:
    SERVICE: cartservice
    DIR: src/${SERVICE}/src

build_and_push_checkoutservice:
  extends: .build_and_push
  variables:
    SERVICE: checkoutservice
    DIR: src/${SERVICE}

build_and_push_currencyservice:
  extends: .build_and_push
  variables:
    SERVICE: currencyservice
    DIR: src/${SERVICE}

build_and_push_emailservice:
  extends: .build_and_push
  variables:
    SERVICE: emailservice
    DIR: src/${SERVICE}

build_and_push_frontend:
  extends: .build_and_push
  variables:
    SERVICE: frontend
    DIR: src/${SERVICE}

build_and_push_loadgenerator:
  extends: .build_and_push
  variables:
    SERVICE: loadgenerator
    DIR: src/${SERVICE}

build_and_push_paymentservice:
  extends: .build_and_push
  variables:
    SERVICE: paymentservice
    DIR: src/${SERVICE}

build_and_push_productcatalogservice:
  extends: .build_and_push
  variables:
    SERVICE: productcatalogservice
    DIR: src/${SERVICE}

build_and_push_recommendationservice:
  extends: .build_and_push
  variables:
    SERVICE: recommendationservice
    DIR: src/${SERVICE}

build_and_push_shippingservice:
  extends: .build_and_push
  variables:
    SERVICE: shippingservice
    DIR: src/${SERVICE}

